use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use chrono::{DateTime, Utc};
use sha2::{Digest, Sha256};

/// A compressed, deterministic summary of a set of FHIR resources.
/// Generated by formatting FHIR data as plain text — NOT by LLM call.
/// Zero token cost. Reproducible. Auditable.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct FhirSummary {
    /// Compressed plain-text summary for LLM consumption.
    pub text: String,
    /// Number of source FHIR resources summarized.
    pub source_count: usize,
    /// SHA-256 hash of source resource IDs — cache invalidation key.
    pub source_hash: String,
    pub created_at: DateTime<Utc>,
}

/// Pre-computed encounter context shared across all agents in an encounter.
/// Avoids each agent independently fetching and formatting the same FHIR data.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct EncounterContext {
    pub encounter_id: String,
    pub patient_id: String,
    /// Compressed medication list (active MedicationRequests).
    pub medication_summary: Option<FhirSummary>,
    /// Compressed problem list (active Conditions).
    pub problem_summary: Option<FhirSummary>,
    /// Compressed allergy list (AllergyIntolerances).
    pub allergy_summary: Option<FhirSummary>,
    /// Total token usage across all agents in this encounter.
    pub total_input_tokens: u64,
    pub total_output_tokens: u64,
    /// When this context was last refreshed.
    pub refreshed_at: DateTime<Utc>,
}

impl EncounterContext {
    pub fn new(encounter_id: impl Into<String>, patient_id: impl Into<String>) -> Self {
        Self {
            encounter_id: encounter_id.into(),
            patient_id: patient_id.into(),
            medication_summary: None,
            problem_summary: None,
            allergy_summary: None,
            total_input_tokens: 0,
            total_output_tokens: 0,
            refreshed_at: Utc::now(),
        }
    }

    /// Add token usage from an agent call.
    pub fn record_tokens(&mut self, input_tokens: u64, output_tokens: u64) {
        self.total_input_tokens += input_tokens;
        self.total_output_tokens += output_tokens;
    }

    /// Build a combined context string for injection into LLM prompts.
    /// Only includes sections that have data. Deterministic and reproducible.
    pub fn to_prompt_context(&self) -> String {
        let mut sections = Vec::new();

        if let Some(ref meds) = self.medication_summary {
            if !meds.text.is_empty() {
                let label = if meds.source_count == 1 { "item" } else { "items" };
                sections.push(format!(
                    "Active Medications ({} {}):\n{}",
                    meds.source_count, label, meds.text
                ));
            }
        }

        if let Some(ref problems) = self.problem_summary {
            if !problems.text.is_empty() {
                let label = if problems.source_count == 1 { "item" } else { "items" };
                sections.push(format!(
                    "Active Problems ({} {}):\n{}",
                    problems.source_count, label, problems.text
                ));
            }
        }

        if let Some(ref allergies) = self.allergy_summary {
            if !allergies.text.is_empty() {
                let label = if allergies.source_count == 1 { "item" } else { "items" };
                sections.push(format!(
                    "Allergies ({} {}):\n{}",
                    allergies.source_count, label, allergies.text
                ));
            }
        }

        if sections.is_empty() {
            return String::new();
        }

        sections.join("\n\n")
    }
}

// ── Deterministic FHIR Summarizers ───────────────────────────────
// These take plain data (not FHIR types) and produce FhirSummary.
// Callers extract fields from FHIR resources before calling.

/// A single medication entry for summarization.
#[derive(Debug, Clone)]
pub struct MedicationEntry {
    pub name: String,
    pub dosage: Option<String>,
    pub route: Option<String>,
    pub status: String,
    pub id: String,
}

/// Summarize a list of medications into a FhirSummary.
/// Format: "- Drug Name (dosage, route) [status]" per line.
/// Only active medications are included.
pub fn summarize_medications(medications: &[MedicationEntry]) -> FhirSummary {
    let active: Vec<&MedicationEntry> = medications
        .iter()
        .filter(|m| m.status == "active")
        .collect();

    let text = active
        .iter()
        .map(|m| {
            let mut parts = vec![m.name.clone()];
            if let Some(ref dosage) = m.dosage {
                parts.push(dosage.clone());
            }
            if let Some(ref route) = m.route {
                parts.push(route.clone());
            }
            format!("- {} [{}]", parts.join(", "), m.status)
        })
        .collect::<Vec<_>>()
        .join("\n");

    let source_hash =
        compute_source_hash(&active.iter().map(|m| m.id.as_str()).collect::<Vec<_>>());

    FhirSummary {
        text,
        source_count: active.len(),
        source_hash,
        created_at: Utc::now(),
    }
}

/// A single problem/condition entry for summarization.
#[derive(Debug, Clone)]
pub struct ProblemEntry {
    pub display: String,
    pub icd10_code: Option<String>,
    pub status: String,
    pub id: String,
}

/// Summarize a list of conditions/problems into a FhirSummary.
/// Format: "- Display Text (ICD-10: code) [status]" per line.
/// Only active conditions are included.
pub fn summarize_problems(problems: &[ProblemEntry]) -> FhirSummary {
    let active: Vec<&ProblemEntry> = problems
        .iter()
        .filter(|p| p.status == "active")
        .collect();

    let text = active
        .iter()
        .map(|p| {
            if let Some(ref code) = p.icd10_code {
                format!("- {} (ICD-10: {}) [{}]", p.display, code, p.status)
            } else {
                format!("- {} [{}]", p.display, p.status)
            }
        })
        .collect::<Vec<_>>()
        .join("\n");

    let source_hash =
        compute_source_hash(&active.iter().map(|p| p.id.as_str()).collect::<Vec<_>>());

    FhirSummary {
        text,
        source_count: active.len(),
        source_hash,
        created_at: Utc::now(),
    }
}

/// A single allergy entry for summarization.
#[derive(Debug, Clone)]
pub struct AllergyEntry {
    pub substance: String,
    pub reaction: Option<String>,
    pub severity: Option<String>,
    pub id: String,
}

/// Summarize a list of allergies into a FhirSummary.
/// Format: "- Substance (reaction, severity)" per line.
/// All allergies are included regardless of status.
pub fn summarize_allergies(allergies: &[AllergyEntry]) -> FhirSummary {
    let text = allergies
        .iter()
        .map(|a| {
            let mut detail = Vec::new();
            if let Some(ref reaction) = a.reaction {
                detail.push(reaction.clone());
            }
            if let Some(ref severity) = a.severity {
                detail.push(severity.clone());
            }
            if detail.is_empty() {
                format!("- {}", a.substance)
            } else {
                format!("- {} ({})", a.substance, detail.join(", "))
            }
        })
        .collect::<Vec<_>>()
        .join("\n");

    let source_hash =
        compute_source_hash(&allergies.iter().map(|a| a.id.as_str()).collect::<Vec<_>>());

    FhirSummary {
        text,
        source_count: allergies.len(),
        source_hash,
        created_at: Utc::now(),
    }
}

/// Compute a deterministic SHA-256 hash from sorted resource IDs.
/// Sorting ensures the hash is order-independent — same set of IDs always
/// produces the same hash regardless of FHIR API return order.
fn compute_source_hash(ids: &[&str]) -> String {
    let mut sorted = ids.to_vec();
    sorted.sort();
    let mut hasher = Sha256::new();
    for id in sorted {
        hasher.update(id.as_bytes());
        hasher.update(b"|"); // separator prevents "ab"+"c" == "a"+"bc"
    }
    format!("{:x}", hasher.finalize())
}

// ── Encounter Context Cache ──────────────────────────────────────

/// Thread-safe, in-memory cache of EncounterContext keyed by encounter_id.
/// Uses Mutex<HashMap> (not DashMap) to avoid adding a dependency.
///
/// Cache invalidation: callers check FhirSummary.source_hash against
/// current resource IDs. If hash mismatches, regenerate the summary.
#[derive(Debug, Clone)]
pub struct EncounterContextCache {
    inner: Arc<Mutex<HashMap<String, EncounterContext>>>,
}

impl EncounterContextCache {
    pub fn new() -> Self {
        Self {
            inner: Arc::new(Mutex::new(HashMap::new())),
        }
    }

    /// Get a cached context, or None if not cached.
    pub fn get(&self, encounter_id: &str) -> Option<EncounterContext> {
        match self.inner.lock() {
            Ok(map) => map.get(encounter_id).cloned(),
            Err(e) => {
                tracing::warn!("encounter context cache lock poisoned on get: {e}");
                None
            }
        }
    }

    /// Insert or update a context.
    pub fn put(&self, ctx: EncounterContext) {
        match self.inner.lock() {
            Ok(mut map) => { map.insert(ctx.encounter_id.clone(), ctx); }
            Err(e) => tracing::warn!("encounter context cache lock poisoned on put: {e}"),
        }
    }

    /// Remove a context (e.g., when encounter closes).
    pub fn remove(&self, encounter_id: &str) -> Option<EncounterContext> {
        match self.inner.lock() {
            Ok(mut map) => map.remove(encounter_id),
            Err(e) => {
                tracing::warn!("encounter context cache lock poisoned on remove: {e}");
                None
            }
        }
    }

    /// Check if a cached summary is still valid by comparing source hashes.
    /// Returns true if the cached hash matches the current hash.
    pub fn is_summary_valid(cached: &FhirSummary, current_hash: &str) -> bool {
        cached.source_hash == current_hash
    }

    /// Get the number of cached contexts.
    pub fn len(&self) -> usize {
        self.inner.lock().map(|m| m.len()).unwrap_or(0)
    }

    /// Check if cache is empty.
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Record token usage for an encounter (no-op if encounter not cached).
    pub fn record_tokens(&self, encounter_id: &str, input_tokens: u64, output_tokens: u64) {
        if let Ok(mut map) = self.inner.lock() {
            if let Some(ctx) = map.get_mut(encounter_id) {
                ctx.record_tokens(input_tokens, output_tokens);
            }
        }
    }
}

impl Default for EncounterContextCache {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Medication summarization ──

    #[test]
    fn summarize_medications_formats_correctly() {
        let meds = vec![
            MedicationEntry {
                name: "Metformin".into(),
                dosage: Some("500mg BID".into()),
                route: Some("oral".into()),
                status: "active".into(),
                id: "med-1".into(),
            },
            MedicationEntry {
                name: "Lisinopril".into(),
                dosage: Some("10mg daily".into()),
                route: None,
                status: "active".into(),
                id: "med-2".into(),
            },
            MedicationEntry {
                name: "Discontinued Drug".into(),
                dosage: None,
                route: None,
                status: "stopped".into(),
                id: "med-3".into(),
            },
        ];

        let summary = summarize_medications(&meds);
        assert_eq!(summary.source_count, 2); // only active
        assert!(summary.text.contains("Metformin"));
        assert!(summary.text.contains("Lisinopril"));
        assert!(!summary.text.contains("Discontinued")); // filtered out
        assert!(summary.text.contains("500mg BID"));
        assert!(summary.text.contains("oral"));
    }

    #[test]
    fn summarize_medications_empty_list() {
        let summary = summarize_medications(&[]);
        assert_eq!(summary.source_count, 0);
        assert!(summary.text.is_empty());
    }

    // ── Problem summarization ──

    #[test]
    fn summarize_problems_with_icd10() {
        let problems = vec![
            ProblemEntry {
                display: "Type 2 Diabetes".into(),
                icd10_code: Some("E11.9".into()),
                status: "active".into(),
                id: "cond-1".into(),
            },
            ProblemEntry {
                display: "Essential Hypertension".into(),
                icd10_code: Some("I10".into()),
                status: "active".into(),
                id: "cond-2".into(),
            },
        ];

        let summary = summarize_problems(&problems);
        assert_eq!(summary.source_count, 2);
        assert!(summary.text.contains("E11.9"));
        assert!(summary.text.contains("I10"));
        assert!(summary.text.contains("Type 2 Diabetes"));
    }

    #[test]
    fn summarize_problems_without_icd10() {
        let problems = vec![ProblemEntry {
            display: "Chronic back pain".into(),
            icd10_code: None,
            status: "active".into(),
            id: "cond-1".into(),
        }];

        let summary = summarize_problems(&problems);
        assert!(summary.text.contains("Chronic back pain"));
        assert!(!summary.text.contains("ICD-10"));
    }

    // ── Allergy summarization ──

    #[test]
    fn summarize_allergies_with_details() {
        let allergies = vec![
            AllergyEntry {
                substance: "Penicillin".into(),
                reaction: Some("hives".into()),
                severity: Some("moderate".into()),
                id: "allergy-1".into(),
            },
            AllergyEntry {
                substance: "Sulfa drugs".into(),
                reaction: None,
                severity: None,
                id: "allergy-2".into(),
            },
        ];

        let summary = summarize_allergies(&allergies);
        assert_eq!(summary.source_count, 2);
        assert!(summary.text.contains("Penicillin (hives, moderate)"));
        assert!(summary.text.contains("- Sulfa drugs"));
    }

    // ── Source hash ──

    #[test]
    fn source_hash_is_deterministic() {
        let h1 = compute_source_hash(&["a", "b", "c"]);
        let h2 = compute_source_hash(&["c", "a", "b"]); // different order
        assert_eq!(h1, h2); // sorted internally
        assert_eq!(h1.len(), 64); // SHA-256 hex
    }

    #[test]
    fn source_hash_changes_with_different_ids() {
        let h1 = compute_source_hash(&["a", "b"]);
        let h2 = compute_source_hash(&["a", "c"]);
        assert_ne!(h1, h2);
    }

    // ── EncounterContext ──

    #[test]
    fn encounter_context_to_prompt_empty() {
        let ctx = EncounterContext::new("enc-1", "patient-1");
        assert!(ctx.to_prompt_context().is_empty());
    }

    #[test]
    fn encounter_context_to_prompt_with_data() {
        let mut ctx = EncounterContext::new("enc-1", "patient-1");
        ctx.medication_summary = Some(FhirSummary {
            text: "- Metformin, 500mg BID [active]".into(),
            source_count: 1,
            source_hash: "abc".into(),
            created_at: Utc::now(),
        });
        ctx.allergy_summary = Some(FhirSummary {
            text: "- Penicillin (hives)".into(),
            source_count: 1,
            source_hash: "def".into(),
            created_at: Utc::now(),
        });

        let prompt = ctx.to_prompt_context();
        assert!(prompt.contains("Active Medications (1 item)"));
        assert!(prompt.contains("Metformin"));
        assert!(prompt.contains("Allergies (1 item)"));
        assert!(prompt.contains("Penicillin"));
    }

    #[test]
    fn encounter_context_record_tokens() {
        let mut ctx = EncounterContext::new("enc-1", "patient-1");
        ctx.record_tokens(100, 50);
        ctx.record_tokens(200, 100);
        assert_eq!(ctx.total_input_tokens, 300);
        assert_eq!(ctx.total_output_tokens, 150);
    }

    // ── Cache ──

    #[test]
    fn cache_put_and_get() {
        let cache = EncounterContextCache::new();
        let ctx = EncounterContext::new("enc-1", "patient-1");
        cache.put(ctx);

        let retrieved = cache.get("enc-1").unwrap();
        assert_eq!(retrieved.encounter_id, "enc-1");
        assert_eq!(retrieved.patient_id, "patient-1");
    }

    #[test]
    fn cache_miss_returns_none() {
        let cache = EncounterContextCache::new();
        assert!(cache.get("nonexistent").is_none());
    }

    #[test]
    fn cache_remove() {
        let cache = EncounterContextCache::new();
        cache.put(EncounterContext::new("enc-1", "patient-1"));
        assert_eq!(cache.len(), 1);

        let removed = cache.remove("enc-1");
        assert!(removed.is_some());
        assert_eq!(cache.len(), 0);
    }

    #[test]
    fn cache_is_summary_valid() {
        let summary = FhirSummary {
            text: "test".into(),
            source_count: 1,
            source_hash: "abc123".into(),
            created_at: Utc::now(),
        };
        assert!(EncounterContextCache::is_summary_valid(&summary, "abc123"));
        assert!(!EncounterContextCache::is_summary_valid(
            &summary,
            "different"
        ));
    }

    #[test]
    fn cache_record_tokens() {
        let cache = EncounterContextCache::new();
        cache.put(EncounterContext::new("enc-1", "patient-1"));
        cache.record_tokens("enc-1", 100, 50);
        cache.record_tokens("enc-1", 200, 100);

        let ctx = cache.get("enc-1").unwrap();
        assert_eq!(ctx.total_input_tokens, 300);
        assert_eq!(ctx.total_output_tokens, 150);
    }
}
